# -*- coding: utf-8 -*-
"""NLP Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RB2rlIAB3SixQGoqc9aLsFG69CBpiMQ7
"""

!pip install -U nltk
!pip install beautifulsoup4

import nltk
import re
from pprint import pprint

text = "Here are some test strings: hello, Hello, cat, cot, cut, and more."

# [a-z]+
print("Pattern [a-z]+ matches:")
nltk.re_show(r'\b[a-z]+', text) #here i put \b to make sure it matches whole word instead of part of the word
print("\n")

# [A-Z][a-z]+
print("Pattern [A-Z][a-z]+ matches:")
nltk.re_show(r'[A-Z][a-z]+', text)
print("\n")

# c[aeiou]{1,2}t
print("Pattern c[aeiou]{1,2}t matches:")
nltk.re_show(r'c[aeiou]{1,2}t', text)

"""# Question 2"""

from urllib import request
from bs4 import BeautifulSoup

def get_text_from_url(url):

    response = request.urlopen(url)
    html = response.read().decode('utf8')


    soup = BeautifulSoup(html, 'html.parser')
    text = soup.get_text()


    text = ' '.join(text.split())

    return text

url = 'https://www.dsu.edu.pk/contact-us/'
content = get_text_from_url(url)
print(content)

"""# Question 3"""

from urllib import request
from bs4 import BeautifulSoup
import nltk
import re

def get_text_from_url(url):

    response = request.urlopen(url)
    html = response.read().decode('utf8')

    soup = BeautifulSoup(html, 'html.parser')
    text = soup.get_text()


#    text = ' '.join(text.split())

    return text

url = 'https://www.dsu.edu.pk/contact-us/'
content = get_text_from_url(url)

import nltk

nltk.download('punkt_tab') # download the 'punkt_tab' collection

sentences = nltk.sent_tokenize(content)

tokens = [nltk.word_tokenize(sentence) for sentence in sentences]

#phone_pattern = re.compile(r'\+?\d[\d\-\(\)\s]{7,}\d')
phone_pattern = re.compile(r'\b(?:Phone #|Cell #)\s*([\d-]+(?:\s*,\s*[\d-]+)*)\b')

email_pattern = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b')

phone_numbers = phone_pattern.findall(content)
email_addresses = email_pattern.findall(content)

print("Phone Numbers Found:", phone_numbers)
print("Email Addresses Found:", email_addresses)

"""# Question 4"""

import nltk
from nltk.stem import PorterStemmer, LancasterStemmer
nltk.download('punkt')

sample_text = "The quick brown foxes are jumping over the lazy dogs. They are running quickly and happily."

words = nltk.word_tokenize(sample_text)
print("Tokenized Words:", words)

porter_stemmer = PorterStemmer()
porter_stemmed_words = [porter_stemmer.stem(word) for word in words]
print("Porter Stemmer Results:", porter_stemmed_words)

lancaster_stemmer = LancasterStemmer()
lancaster_stemmed_words = [lancaster_stemmer.stem(word) for word in words]
print("Lancaster Stemmer Results:", lancaster_stemmed_words)